<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Chap02_a2.aspx.cs" Inherits="midtermReview.Chap02_a2" %>
<%-- 디렉티브 Page, --%>
<!DOCTYPE html>



<script runat="server">
                    protected void Page_Load(object sender, EventArgs e)
                    {
                    myTimeLabel.Text = DateTime.Now.ToString();
                    }
void Click(Object s, EventArgs e)
{
messageLabel.Text = nameTextBox.Text;
}


</script>


<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Chapter2</title>
</head>
<body>
    <form id="form1" runat="server">
		 <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Delius|Gloria+Hallelujah|Lobster|Merienda+One|Indie+Flower|Pacifico">
        <div>
			        <p style="background-color:aliceblue; color:darkblue; font-size:20px;">Chapter2 Slide10</p>

                    <p style="color:blueviolet; font-family:Delius;">
                    The time is now:
                    <%-- Display the current date and time --%>
                    <asp:Label ID="myTimeLabel" runat="server" /> <br />
						▶ Display the current date and timeDateTime.Now.ToString();
                    </p>

                    <p style="color:cadetblue; font-family:Delius;">
                    <%-- Declare the title as string and set it --%>
                    <% string k = "This is generated by a code render block."; %>
                    <%= k %> <br />
						▶ Declare the title as string and set it
                    </p>
        </div>
		<div>
				    <p style="background-color:aliceblue; color:darkblue; font-size:20px;">Chapter2 Slide24</p>
			        <% int a = 7;
						int b = 8;
						int sum =a + b;
						int multi = a * b; %>
			        <p style="color:cadetblue; font-family:Delius;">
						<% Response.Write("a is : " + a + " <br> b is : " + b + " <br> sum is : " 
			               + sum + " <br> multi is : " + multi + "</p>");%>

		</div>
		<div>
			 <p style="background-color:aliceblue; color:darkblue; font-size:20px;">Chapter2 Slide27</p>
			    <p style="color:cadetblue; font-family:Delius;">
			   <% string Title = "String Test"; %>
               <% =Title %>    </p>
		</div>
		<div>
			 <p style="background-color:aliceblue; color:darkblue; font-size:20px;">Chapter2 Slide28</p>
			    <p style="color:cadetblue; font-family:Delius;">
			    <%: "5 is >3" %>
		</div>
		<div>
			 <p style="background-color:aliceblue; color:darkblue; font-size:20px;">Chapter2 Slide38</p>
			    <div style="color:cadetblue; font-family:Delius;">
					<asp:TextBox id="nameTextBox" runat="server" />
                    <asp:Button id="submitButton" runat="server" Text="Click Me" OnClick="Click" />
                    <asp:Label id="messageLabel" runat="server" />
					</div>



		</div>
    </form>
</body>
</html>
